import { standings } from "@/weeklyMatches"
export const dummyData: standings = {
  data: [
    {
      "Wins": 6,
      "Losses": 2,
      "Team": "MIA",
      "TeamName": "Dolphins",
    },
    {
      "Wins": 5,
      "Losses": 3,
      "Team": "BUF",
      "TeamName": "Bills",
    },
    {
      "Wins": 4,
      "Losses": 3,
      "Team": "NYJ",
      "TeamName": "Jets",
    },
    {
      "Wins": 2,
      "Losses": 6,
      "Team": "NE",
      "TeamName": "Patriots",
    },
    {
      "Wins": 6,
      "Losses": 2,
      "Team": "BAL",
      "TeamName": "Ravens",
    },
    {
      "Wins": 4,
      "Losses": 3,
      "Team": "CIN",
      "TeamName": "Bengals",
    },
    {
      "Wins": 4,
      "Losses": 3,
      "Team": "CLE",
      "TeamName": "Browns",
    },
    {
      "Wins": 4,
      "Losses": 3,
      "Team": "PIT",
      "TeamName": "Steelers",
    },
    {
      "Wins": 6,
      "Losses": 2,
      "Team": "JAX",
      "TeamName": "Jaguars",
    },
    {
      "Wins": 3,
      "Losses": 4,
      "Team": "HOU",
      "TeamName": "Texans",
    },
    {
      "Wins": 3,
      "Losses": 4,
      "Team": "TEN",
      "TeamName": "Titans",
    },
    {
      "Wins": 3,
      "Losses": 5,
      "Team": "IND",
      "TeamName": "Colts",
    },
    {
      "Wins": 6,
      "Losses": 2,
      "Team": "KC",
      "TeamName": "Chiefs",
    },
    {
      "Wins": 3,
      "Losses": 4,
      "Team": "LAC",
      "TeamName": "Chargers",
    },
    {
      "Wins": 3,
      "Losses": 5,
      "Team": "DEN",
      "TeamName": "Broncos",
    },
    {
      "Wins": 3,
      "Losses": 5,
      "Team": "LV",
      "TeamName": "Raiders",
    },
    {
      "Wins": 7,
      "Losses": 1,
      "Team": "PHI",
      "TeamName": "Eagles",
    },
    {
      "Wins": 5,
      "Losses": 2,
      "Team": "DAL",
      "TeamName": "Cowboys",
    },
    {
      "Wins": 3,
      "Losses": 5,
      "Team": "WAS",
      "TeamName": "Football Team",
    },
    {
      "Wins": 2,
      "Losses": 6,
      "Team": "NYG",
      "TeamName": "Giants",
    },
    {
      "Wins": 6,
      "Losses": 2,
      "Team": "DET",
      "TeamName": "Lions",
    },
    {
      "Wins": 4,
      "Losses": 4,
      "Team": "MIN",
      "TeamName": "Vikings",
    },
    {
      "Wins": 2,
      "Losses": 5,
      "Team": "GB",
      "TeamName": "Packers",
    },
    {
      "Wins": 2,
      "Losses": 6,
      "Team": "CHI",
      "TeamName": "Bears",
    },
    {
      "Wins": 4,
      "Losses": 4,
      "Team": "ATL",
      "TeamName": "Falcons",
    },
    {
      "Wins": 4,
      "Losses": 4,
      "Team": "NO",
      "TeamName": "Saints",
    },
    {
      "Wins": 3,
      "Losses": 4,
      "Team": "TB",
      "TeamName": "Buccaneers",
    },
    {
      "Wins": 1,
      "Losses": 6,
      "Team": "CAR",
      "TeamName": "Panthers",
    },
    {
      "Wins": 5,
      "Losses": 2,
      "Team": "SEA",
      "TeamName": "Seahawks",
    }]}