export const dummyData = {
    data: [
      {
        Team: "DAL",
        Touchdowns: 18,
        RushingYards: 723,
        PassingYards: 1364,
        OffensiveYardsPerPlay: 4,
        RushingYardsPerAttempt: 3,
        PassingYardsPerAttempt: 5.3,
        Takeaways: 11,
        Sacks: 16,
        FumblesRecovered: 3,
        PassesDefended: 27,
        OpponentPassingInterceptions: 5,
      },
      {
        Team: "DEN",
        Touchdowns: 17,
        RushingYards: 824,
        PassingYards: 1308,
        OffensiveYardsPerPlay: 4.1,
        RushingYardsPerAttempt: 3.7,
        PassingYardsPerAttempt: 5,
        Takeaways: 11,
        Sacks: 15,
        FumblesRecovered: 4,
        PassesDefended: 26,
        OpponentPassingInterceptions: 3,
      },
      {
        Team: "KC",
        Touchdowns: 22,
        RushingYards: 954,
        PassingYards: 1650,
        OffensiveYardsPerPlay: 5,
        RushingYardsPerAttempt: 4.1,
        PassingYardsPerAttempt: 6.2,
        Takeaways: 14,
        Sacks: 20,
        FumblesRecovered: 5,
        PassesDefended: 30,
        OpponentPassingInterceptions: 6,
      },
      {
        Team: "NYG",
        Touchdowns: 14,
        RushingYards: 638,
        PassingYards: 1275,
        OffensiveYardsPerPlay: 3.8,
        RushingYardsPerAttempt: 2.9,
        PassingYardsPerAttempt: 5.1,
        Takeaways: 9,
        Sacks: 18,
        FumblesRecovered: 2,
        PassesDefended: 25,
        OpponentPassingInterceptions: 4,
      },
      {
        Team: "NE",
        Touchdowns: 19,
        RushingYards: 890,
        PassingYards: 1442,
        OffensiveYardsPerPlay: 4.4,
        RushingYardsPerAttempt: 3.8,
        PassingYardsPerAttempt: 5.9,
        Takeaways: 12,
        Sacks: 17,
        FumblesRecovered: 4,
        PassesDefended: 28,
        OpponentPassingInterceptions: 4,
      },
      {
        Team: "GB",
        Touchdowns: 20,
        RushingYards: 753,
        PassingYards: 1578,
        OffensiveYardsPerPlay: 5.1,
        RushingYardsPerAttempt: 4.2,
        PassingYardsPerAttempt: 7.2,
        Takeaways: 13,
        Sacks: 19,
        FumblesRecovered: 6,
        PassesDefended: 29,
        OpponentPassingInterceptions: 5,
      },
      // Add more teams here...
    ],
  };
  